var userAPI = {
  "login": "MLamson",
  "id": 10374310,
  "avatar_url": "https://avatars.githubusercontent.com/u/10374310?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MLamson",
  "html_url": "https://github.com/MLamson",
  "followers_url": "https://api.github.com/users/MLamson/followers",
  "following_url": "https://api.github.com/users/MLamson/following{/other_user}",
  "gists_url": "https://api.github.com/users/MLamson/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MLamson/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MLamson/subscriptions",
  "organizations_url": "https://api.github.com/users/MLamson/orgs",
  "repos_url": "https://api.github.com/users/MLamson/repos",
  "events_url": "https://api.github.com/users/MLamson/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MLamson/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mark Lamson",
  "company": "",
  "blog": "",
  "location": "",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 14,
  "public_gists": 0,
  "followers": 1,
  "following": 0,
  "created_at": "2015-01-02T17:57:09Z",
  "updated_at": "2015-01-26T15:19:40Z"
}